

CC=g++
CFLAGS=-L/usr/lib/x86_64-linux-gnu/ -lGL -lglut -lGLU -lm

shape: shape.o ParseInput.o Instruction.o Forward.o Jump.o Rotate.o Repeat.o window.h
	$(CC) $(CFLAGS) shape.o ParseInput.o Instruction.o Forward.o Jump.o Rotate.o Repeat.o -o shape
    
shape.o: shape.cpp ParseInput.h window.h Exceptions.h
	$(CC) $(CFLAGS) -c shape.cpp

ParseInput.o: ParseInput.cpp Exceptions.h Instruction.h Forward.h Jump.h Rotate.h Repeat.h
	$(CC) -c ParseInput.cpp

Instruction.o: Instruction.cpp Instruction.h
	$(CC) -c Instruction.cpp

Forward.o: Forward.cpp Forward.h Instruction.h
	$(CC) -c Forward.cpp

Jump.o: Jump.cpp Jump.h Instruction.h
	$(CC) -c Jump.cpp
    
Rotate.o: Rotate.cpp Rotate.h Instruction.h
	$(CC) -c Rotate.cpp
    
Repeat.o: Repeat.cpp Repeat.h ParseInput.h
	$(CC) -c Repeat.cpp

clean:
	rm -rf *o shape
