

CC=g++
CFLAGS=-lGL -lglut -lGLU   -lm
LDFLAGS=
SOURCES=ParseInput.cpp Instruction.cpp shape.cpp  Forward.cpp Jump.cpp Repeat.cpp Rotate.cpp    
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=shape

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *o shape
